name: Overdue Accounts Monitor

on:
  schedule:
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Overdue Accounts Monitor
        env:
          user_url: ${{ secrets.user_url }}
          invoices_url: ${{ secrets.invoices_url }}
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
          slack_token: ${{ secrets.slack_token }}
        run: |
          python overdue_accounts.py

      - name: Ping Healthchecks
        run: curl -fsS ${{ secrets.HealthCheck_Overdue_Accounts }} || true

      - name: Ping Healthchecks (failure)
        if: failure()
        run: curl -fsS ${{ secrets.HealthCheck_Overdue_Accounts }}/fail || true